
name: CI workflow Test

on:
 push: 

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        sudo pip install --ignore-installed -r flask-3tier-docker-app/app/requirements.txt
           

    - name: Run the Python app
      run: python app.py
        
      

      
