name: Installed Versions
on:
 push:
   branches: [main]

jobs:
  Display_Version:
     runs-on: ubuntu-latest

     steps:
       - name: Display Docker Version
         run:  docker --V

       - name: Display Python Version
         run:  python --V

       - name: Display Node Version
         run:  node --V

       - name: Display Git Version
         run:  git --V


         

   
