name: Nginx App
on: 
 push: 
  branches: [main]

jobs:
  BuildJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Image
        run:  |
          docker build -t nginxapp:v1 .

        


        
