name: Environment Variables
on:
  push:
     branches: [main]

env:
  APP_NAME: myapp

jobs:
  Scope:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: staging
      
    steps:
      - name: Prints the variable at workflow , job and step level
        env:   
          VERSION: 1.0.0
        run: |
         echo "App is: $APP_NAME "
         echo "Environment is: $ENVIRONMENT "
         echo "Version is: $VERSION "

      - name: Checking access of the variables
        run: |
         echo "$APP_NAME :workflow variables has scope from steps level"
         echo "$ENVIRONMENT :job variables has scope from step level"
         echo "$VERSION :step variables has scope from step level"
           
      
           
    
  
     
