name: Job Outputs
on:
 push:
   branches: [main]

jobs:
  show_date:
    runs-on: ubuntu-latest
    steps:
      - name: Show todays date
        run:  echo "date=$(date)" >> $GITHUB_OUTPUT


        
    

    
    
