name: Job Outputs
on:
 push:
   branches: [main]

jobs:
  set_date:
    runs-on: ubuntu-latest
    steps:
      - name: Set todays date
        run:  echo "date=$(date)" >> $GITHUB_OUTPUT

  show_date:
    runs-on: ubuntu-latest
    steps:
      - name: Show the set date
        run:  echo "{{ needs.set_date.outputs.date }}"
        
        


        
    

    
    
