name: PR Validation
on:
 pull_request: 
  branches: [main]

jobs: 
  file-size-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checks if sny file greater than 1MB
        run: |
         Limit=1048576
         for i in $( git diff --name-only origin/main...HEAD )
         do
           Size=$( stat -c %s "$i" )
           if [ "$Size" -gt "$Limit" ];then
               echo "File size: $Size"
               echo "File is larger"
               exit 1
           fi
         done  
         
  branch-name-check:
    runs-on: ubuntu-latest
    steps:
      - name: Read the branch name
        run:  echo "Branch:- ${{ github.head_ref }}"

      - name: Validate file
        run:  |
         for i in $GITHUB_HEAD_REF;do
           if [[ "$i" != feature/* && "$i" != fix/* && "$i" != docs/* ]];then
               echo "Invalid pattern: $i"
               exit 1
           fi
         done

  pr-body-check:
    runs-on: ubuntu-latest
    steps:
      - name: Reads the PR body
        run:  echo "${{ github.event.pull_request.body }}"

      - name: Check PR body
        if:   ${{ github.event.pull_request.body == '' }}
        run:  echo "PR body is empty"


        
         
          
        
