name: PR Check
on:
  pull_request:
    branches: [main]

jobs:
  Notify:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run:  echo 'PR check running for the branch: ${{ github.ref_name }}'
