name: My Secret Message
on:
 push:

jobs:
  check_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checks if secret exists or not
        env:  
          SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          if [ -n "$SECRET" ]; then
             echo "The secret is set : true"
          else
             echo "No Secrets found"
          fi 

  print_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Prints the secrets
        env:  
          SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
        run:  echo "$SECRET"





      
      
