name: Self Hosted Runner
on:
  push:
    branches: [main]
      
      
jobs:
  Runner:
    runs-on: [self-hosted, custom]
    
    steps:
      - name: Prints Hostname
        run: hostname
       
      - name: Prints working directory
        run: pwd
       
      - name: Create a file
        run:  touch FileCreated.txt


        

      
    
    
  
